### ISSUE TITLE
How to import this library into an ES6 module?

### ISSUE THREAD

**Issue by matteomattei** [commenthol/date-holidays-ical#3]
Hello,
I need to import date-holidays-ical library into an ES6 module but given it does not expose any **default** export, it throws an error.
This is the way I am trying to import it:

`import ical from "date-holidays-ical";`

And this is the error I get:

```
import ical from "date-holidays-ical";
       ^^^^
SyntaxError: The requested module 'date-holidays-ical' does not provide an export named 'default'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Even using a named export **ical** it does not work:

`import {ical} from "date-holidays-ical";`

And this is the error:

```
import {ical} from "date-holidays-ical";
        ^^^^
SyntaxError: The requested module 'date-holidays-ical' does not provide an export named 'ical'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Obviously I cannot use _require_ since my application is a pure ES6 module.
Any hint?

**Comment by commenthol** [comment]
Hi @matteomattei,
Thanks for rising the issue. Sorry for the confusion. PR #5 should have corrected the problem. New package is on its way.

**Comment by matteomattei** [comment]
Thank you!
